name: mkr  
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7  
  - plotly==5.24.1
  - numpy==1.26.4
  - pandas==2.2.3
  - pandas-datareader==0.10.0
  - matplotlib==3.10.0
  - seaborn==0.13.2
  - requests==2.32.3
  - scikit-learn==1.5.1
  - xgboost==2.1.3
  - shap==0.46.0
  #- ta-lib  # Use conda to install